#!/usr/bin/env python3
"""Reconstruct deterministic MX01 boundary surfaces from occupancy intervals."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SHIP_DIR = ROOT / "ships" / "MX01"
DEFAULT_CONFIG = SHIP_DIR / "config" / "mx01_collision_generation.json"


NEIGHBORS = [
    ("x_neg", (-1, 0, 0)),
    ("x_pos", (1, 0, 0)),
    ("y_neg", (0, -1, 0)),
    ("y_pos", (0, 1, 0)),
    ("z_neg", (0, 0, -1)),
    ("z_pos", (0, 0, 1)),
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def rel(path: Path) -> str:
    return str(path.resolve().relative_to(ROOT))


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def resolve_config_path(config: dict, section: str, key: str) -> Path:
    return ROOT / config[section][key]


def build_inside_set(occupancy: dict) -> set[tuple[int, int, int]]:
    inside: set[tuple[int, int, int]] = set()
    for ray in occupancy["rays"]:
        yi = int(ray["y_index"])
        zi = int(ray["z_index"])
        for start, end in ray["x_intervals"]:
            for xi in range(int(start), int(end) + 1):
                inside.add((xi, yi, zi))
    return inside


def axis_edges(centers: list[float], voxel_size: float) -> list[float]:
    if not centers:
        return []
    start = centers[0] - voxel_size * 0.5
    return [round(start + index * voxel_size, 6) for index in range(len(centers) + 1)]


def face_record(orientation: str, xi: int, yi: int, zi: int) -> dict:
    if orientation == "x_neg":
        return {"orientation": orientation, "plane": xi, "u_axis": "y", "v_axis": "z", "u": yi, "v": zi}
    if orientation == "x_pos":
        return {"orientation": orientation, "plane": xi + 1, "u_axis": "y", "v_axis": "z", "u": yi, "v": zi}
    if orientation == "y_neg":
        return {"orientation": orientation, "plane": yi, "u_axis": "x", "v_axis": "z", "u": xi, "v": zi}
    if orientation == "y_pos":
        return {"orientation": orientation, "plane": yi + 1, "u_axis": "x", "v_axis": "z", "u": xi, "v": zi}
    if orientation == "z_neg":
        return {"orientation": orientation, "plane": zi, "u_axis": "x", "v_axis": "y", "u": xi, "v": yi}
    if orientation == "z_pos":
        return {"orientation": orientation, "plane": zi + 1, "u_axis": "x", "v_axis": "y", "u": xi, "v": yi}
    raise RuntimeError(orientation)


def quad_points(face: dict, edges: dict[str, list[float]]) -> list[tuple[float, float, float]]:
    o = face["orientation"]
    p = int(face["plane"])
    u = int(face["u"])
    v = int(face["v"])
    if o in {"x_neg", "x_pos"}:
        x = edges["x"][p]
        y0, y1 = edges["y"][u], edges["y"][u + 1]
        z0, z1 = edges["z"][v], edges["z"][v + 1]
        pts = [(x, y0, z0), (x, y1, z0), (x, y1, z1), (x, y0, z1)]
        return pts if o == "x_pos" else list(reversed(pts))
    if o in {"y_neg", "y_pos"}:
        y = edges["y"][p]
        x0, x1 = edges["x"][u], edges["x"][u + 1]
        z0, z1 = edges["z"][v], edges["z"][v + 1]
        pts = [(x0, y, z0), (x0, y, z1), (x1, y, z1), (x1, y, z0)]
        return pts if o == "y_pos" else list(reversed(pts))
    if o in {"z_neg", "z_pos"}:
        z = edges["z"][p]
        x0, x1 = edges["x"][u], edges["x"][u + 1]
        y0, y1 = edges["y"][v], edges["y"][v + 1]
        pts = [(x0, y0, z), (x1, y0, z), (x1, y1, z), (x0, y1, z)]
        return pts if o == "z_pos" else list(reversed(pts))
    raise RuntimeError(o)


def write_obj(path: Path, faces: list[dict], edges: dict[str, list[float]], object_name: str) -> int:
    vertex_index: dict[tuple[float, float, float], int] = {}
    vertices: list[tuple[float, float, float]] = []
    obj_faces: list[list[int]] = []

    for face in faces:
        indices = []
        for point in quad_points(face, edges):
            if point not in vertex_index:
                vertex_index[point] = len(vertices) + 1
                vertices.append(point)
            indices.append(vertex_index[point])
        obj_faces.append(indices)

    lines = [f"# {object_name} generated by reconstruct_mx01_boundary_surfaces.py", f"o {object_name}", "usemtl MX01_BoundaryRaw"]
    for x, y, z in vertices:
        lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    for indices in obj_faces:
        lines.append("f " + " ".join(str(index) for index in indices))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(vertices)


def write_markdown(path: Path, report: dict) -> None:
    lines = [
        "# MX01 Boundary Reconstruction Report",
        "",
        f"- Method: `{report['method']}`",
        f"- Status: `{report['status']}`",
        f"- Inside voxels: `{report['counts']['inside_voxels']}`",
        f"- Boundary quads: `{report['counts']['boundary_quads']}`",
        f"- OBJ vertices: `{report['counts']['obj_vertices']}`",
        f"- Theoretical max surface error: `{report['fit']['theoretical_max_surface_error']}`",
        "",
        "## Orientation Counts",
        "",
    ]
    for orientation, count in report["orientation_counts"].items():
        lines.append(f"- `{orientation}`: {count}")
    lines.extend(["", "## Notes", "", report["notes"]])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    args = parser.parse_args()

    config_path = args.config.resolve()
    config = load_json(config_path)
    occupancy_path = resolve_config_path(config, "occupancy_outputs", "intervals_json")
    occupancy = load_json(occupancy_path)
    voxel_size = float(occupancy["voxel_size"])
    inside = build_inside_set(occupancy)
    centers = occupancy["axis_centers"]
    edges = {axis: axis_edges(centers[axis], voxel_size) for axis in ("x", "y", "z")}

    faces: list[dict] = []
    orientation_counts: dict[str, int] = {}
    for xi, yi, zi in sorted(inside):
        for orientation, delta in NEIGHBORS:
            neighbor = (xi + delta[0], yi + delta[1], zi + delta[2])
            if neighbor not in inside:
                record = face_record(orientation, xi, yi, zi)
                faces.append(record)
                orientation_counts[orientation] = orientation_counts.get(orientation, 0) + 1
    faces.sort(key=lambda face: (face["orientation"], face["plane"], face["u"], face["v"]))

    faces_json = resolve_config_path(config, "boundary_outputs", "faces_json")
    raw_obj = resolve_config_path(config, "boundary_outputs", "raw_obj")
    report_json = resolve_config_path(config, "boundary_outputs", "report_json")
    report_md = resolve_config_path(config, "boundary_outputs", "report_md")
    manifest_json = resolve_config_path(config, "boundary_outputs", "manifest_json")

    payload = {
        "ship_id": config["ship_id"],
        "method": "voxel_exposed_faces_boundary_v1",
        "voxel_size": voxel_size,
        "axis_edges": edges,
        "faces": faces,
    }
    write_json(faces_json, payload)
    obj_vertices = write_obj(raw_obj, faces, edges, "MX01_BoundarySurface_Raw")
    report = {
        "ship_id": config["ship_id"],
        "method": payload["method"],
        "status": "PASS",
        "counts": {
            "inside_voxels": len(inside),
            "boundary_quads": len(faces),
            "obj_vertices": obj_vertices,
        },
        "orientation_counts": dict(sorted(orientation_counts.items())),
        "fit": {
            "source": "occupancy grid boundary, not final marching-cubes SDF",
            "theoretical_max_surface_error": round(voxel_size * 0.5, 6),
            "voxel_size": voxel_size,
        },
        "source": {"occupancy_intervals": rel(occupancy_path), "occupancy_intervals_sha256": sha256(occupancy_path)},
        "config": {"path": rel(config_path), "sha256": sha256(config_path), "effective_values": config},
        "tools": {
            "reconstruct_mx01_boundary_surfaces.py": {"path": rel(Path(__file__).resolve()), "sha256": sha256(Path(__file__).resolve())}
        },
        "outputs": {"faces_json": rel(faces_json), "raw_obj": rel(raw_obj)},
        "notes": "This is the deterministic exposed-voxel boundary baseline. It is suitable for review and simplification, but it does not yet replace the planned marching-cubes or dual-contouring surface.",
    }
    write_json(report_json, report)
    write_markdown(report_md, report)
    write_json(
        manifest_json,
        {
            "ship_id": config["ship_id"],
            "stage": "boundary_reconstruction",
            "source": report["source"],
            "config": report["config"],
            "outputs": {
                "faces_json": rel(faces_json),
                "faces_json_sha256": sha256(faces_json),
                "raw_obj": rel(raw_obj),
                "raw_obj_sha256": sha256(raw_obj),
                "report_json": rel(report_json),
                "report_md": rel(report_md),
            },
            "tools": report["tools"],
        },
    )
    print(f"Wrote {rel(faces_json)}")
    print(f"Wrote {rel(raw_obj)}")
    print(f"Wrote {rel(report_json)}")
    print(f"Wrote {rel(report_md)}")
    print(f"Wrote {rel(manifest_json)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
