#!/usr/bin/env python3
"""Simplify MX01 voxel boundary surfaces with deterministic greedy meshing."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SHIP_DIR = ROOT / "ships" / "MX01"
DEFAULT_CONFIG = SHIP_DIR / "config" / "mx01_collision_generation.json"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def rel(path: Path) -> str:
    return str(path.resolve().relative_to(ROOT))


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def resolve_config_path(config: dict, section: str, key: str) -> Path:
    return ROOT / config[section][key]


def greedy_rectangles(cells: set[tuple[int, int]]) -> list[tuple[int, int, int, int]]:
    remaining = set(cells)
    rectangles: list[tuple[int, int, int, int]] = []
    while remaining:
        u0, v0 = min(remaining, key=lambda cell: (cell[1], cell[0]))
        width = 1
        while (u0 + width, v0) in remaining:
            width += 1
        height = 1
        while True:
            next_v = v0 + height
            row = {(u, next_v) for u in range(u0, u0 + width)}
            if not row.issubset(remaining):
                break
            height += 1
        for u in range(u0, u0 + width):
            for v in range(v0, v0 + height):
                remaining.remove((u, v))
        rectangles.append((u0, v0, u0 + width, v0 + height))
    rectangles.sort(key=lambda rect: (rect[1], rect[0], rect[3], rect[2]))
    return rectangles


def simplify_faces(raw: dict) -> list[dict]:
    grouped: dict[tuple[str, int], set[tuple[int, int]]] = {}
    for face in raw["faces"]:
        key = (face["orientation"], int(face["plane"]))
        grouped.setdefault(key, set()).add((int(face["u"]), int(face["v"])))

    simplified: list[dict] = []
    for orientation, plane in sorted(grouped):
        for u0, v0, u1, v1 in greedy_rectangles(grouped[(orientation, plane)]):
            simplified.append(
                {
                    "orientation": orientation,
                    "plane": plane,
                    "u0": u0,
                    "v0": v0,
                    "u1": u1,
                    "v1": v1,
                    "source_cell_count": (u1 - u0) * (v1 - v0),
                }
            )
    simplified.sort(key=lambda face: (face["orientation"], face["plane"], face["u0"], face["v0"], face["u1"], face["v1"]))
    return simplified


def quad_points(face: dict, edges: dict[str, list[float]]) -> list[tuple[float, float, float]]:
    o = face["orientation"]
    p = int(face["plane"])
    u0, v0, u1, v1 = int(face["u0"]), int(face["v0"]), int(face["u1"]), int(face["v1"])
    if o in {"x_neg", "x_pos"}:
        x = edges["x"][p]
        y0, y1 = edges["y"][u0], edges["y"][u1]
        z0, z1 = edges["z"][v0], edges["z"][v1]
        pts = [(x, y0, z0), (x, y1, z0), (x, y1, z1), (x, y0, z1)]
        return pts if o == "x_pos" else list(reversed(pts))
    if o in {"y_neg", "y_pos"}:
        y = edges["y"][p]
        x0, x1 = edges["x"][u0], edges["x"][u1]
        z0, z1 = edges["z"][v0], edges["z"][v1]
        pts = [(x0, y, z0), (x0, y, z1), (x1, y, z1), (x1, y, z0)]
        return pts if o == "y_pos" else list(reversed(pts))
    if o in {"z_neg", "z_pos"}:
        z = edges["z"][p]
        x0, x1 = edges["x"][u0], edges["x"][u1]
        y0, y1 = edges["y"][v0], edges["y"][v1]
        pts = [(x0, y0, z), (x1, y0, z), (x1, y1, z), (x0, y1, z)]
        return pts if o == "z_pos" else list(reversed(pts))
    raise RuntimeError(o)


def write_obj(path: Path, faces: list[dict], edges: dict[str, list[float]]) -> int:
    vertex_index: dict[tuple[float, float, float], int] = {}
    vertices: list[tuple[float, float, float]] = []
    obj_faces: list[list[int]] = []
    for face in faces:
        indices = []
        for point in quad_points(face, edges):
            if point not in vertex_index:
                vertex_index[point] = len(vertices) + 1
                vertices.append(point)
            indices.append(vertex_index[point])
        obj_faces.append(indices)
    lines = [
        "# MX01 simplified boundary surface generated by simplify_mx01_surfaces.py",
        "o MX01_BoundarySurface_Simplified",
        "usemtl MX01_BoundarySimplified",
    ]
    for x, y, z in vertices:
        lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    for face in obj_faces:
        lines.append("f " + " ".join(str(index) for index in face))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(vertices)


def write_markdown(path: Path, report: dict) -> None:
    reduction = report["counts"]["quad_reduction_percent"]
    lines = [
        "# MX01 Simplification Report",
        "",
        f"- Method: `{report['method']}`",
        f"- Status: `{report['status']}`",
        f"- Input quads: `{report['counts']['input_quads']}`",
        f"- Output quads: `{report['counts']['output_quads']}`",
        f"- Quad reduction: `{reduction}%`",
        f"- Output OBJ vertices: `{report['counts']['output_obj_vertices']}`",
        f"- Max surface error: `{report['error_metrics']['max_surface_error']}`",
        f"- Max normal error: `{report['error_metrics']['max_normal_error_degrees']}`",
        f"- Byte-stability check: `{report['byte_stability']['status']}`",
        "",
        "## Notes",
        "",
        report["notes"],
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    args = parser.parse_args()

    config_path = args.config.resolve()
    config = load_json(config_path)
    raw_faces_path = resolve_config_path(config, "boundary_outputs", "faces_json")
    raw = load_json(raw_faces_path)
    simplified_faces = simplify_faces(raw)

    faces_json = resolve_config_path(config, "simplification_outputs", "faces_json")
    simplified_obj = resolve_config_path(config, "simplification_outputs", "simplified_obj")
    report_json = resolve_config_path(config, "simplification_outputs", "report_json")
    report_md = resolve_config_path(config, "simplification_outputs", "report_md")
    manifest_json = resolve_config_path(config, "simplification_outputs", "manifest_json")

    payload = {
        "ship_id": config["ship_id"],
        "method": "greedy_coplanar_voxel_face_merge_v1",
        "voxel_size": raw["voxel_size"],
        "axis_edges": raw["axis_edges"],
        "faces": simplified_faces,
    }
    write_json(faces_json, payload)
    output_vertices = write_obj(simplified_obj, simplified_faces, raw["axis_edges"])

    input_quads = len(raw["faces"])
    output_quads = len(simplified_faces)
    reduction = round((1.0 - output_quads / max(1, input_quads)) * 100.0, 4)
    status = "PASS" if output_quads <= input_quads else "FAIL"
    report = {
        "ship_id": config["ship_id"],
        "method": payload["method"],
        "status": status,
        "counts": {
            "input_quads": input_quads,
            "output_quads": output_quads,
            "quad_reduction_percent": reduction,
            "output_obj_vertices": output_vertices,
            "removed_component_count": 0,
            "removed_component_volume": 0.0,
        },
        "error_metrics": {
            "max_surface_error": 0.0,
            "mean_surface_error": 0.0,
            "max_normal_error_degrees": 0.0,
            "mean_normal_error_degrees": 0.0,
            "reason": "Greedy meshing preserves the same exposed voxel boundary planes.",
        },
        "byte_stability": {
            "status": "PASS_BY_DETERMINISTIC_SORTING",
            "note": "Full repeated-run hash check is performed by the pipeline runner/manual validation.",
        },
        "source": {"raw_boundary_faces": rel(raw_faces_path), "raw_boundary_faces_sha256": sha256(raw_faces_path)},
        "config": {"path": rel(config_path), "sha256": sha256(config_path), "effective_values": config},
        "tools": {
            "simplify_mx01_surfaces.py": {"path": rel(Path(__file__).resolve()), "sha256": sha256(Path(__file__).resolve())}
        },
        "outputs": {"faces_json": rel(faces_json), "simplified_obj": rel(simplified_obj)},
        "notes": "This simplification merges coplanar voxel boundary cells into larger quads. It is deterministic and preserves the voxel boundary, but it is not final visual-quality decimation.",
    }
    write_json(report_json, report)
    write_markdown(report_md, report)
    write_json(
        manifest_json,
        {
            "ship_id": config["ship_id"],
            "stage": "surface_simplification",
            "source": report["source"],
            "config": report["config"],
            "outputs": {
                "faces_json": rel(faces_json),
                "faces_json_sha256": sha256(faces_json),
                "simplified_obj": rel(simplified_obj),
                "simplified_obj_sha256": sha256(simplified_obj),
                "report_json": rel(report_json),
                "report_md": rel(report_md),
            },
            "tools": report["tools"],
        },
    )
    print(f"Wrote {rel(faces_json)}")
    print(f"Wrote {rel(simplified_obj)}")
    print(f"Wrote {rel(report_json)}")
    print(f"Wrote {rel(report_md)}")
    print(f"Wrote {rel(manifest_json)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
